# Generated by Django 5.2.6 on 2025-10-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultfileupload',
            name='class_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resultfileupload',
            name='section',
            field=models.CharField(max_length=10),
        ),
        migrations.AddConstraint(
            model_name='resultfileupload',
            constraint=models.UniqueConstraint(fields=('teacher_name', 'class_name', 'section', 'subject_name', 'student_name'), name='unique_result_per_student_subject'),
        ),
    ]
